name: travel_world
description: Travel app
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.3+2
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  fluttertoast: ^3.1.0
  shared_preferences: 0.5.3+4
  firebase_storage: ^3.1.1
  cached_network_image: ^2.0.0
  intl: ^0.15.7
  photo_view: ^0.7.0
  modal_progress_hud: ^0.1.3
  flutter_datetime_picker: 1.2.5
  image_picker: ^0.6.1+4
  url_launcher: ^5.1.3
  auto_size_text: ^2.0.2
  random_string: ^1.1.0
  preload_page_view: ^0.1.4
  path_provider: ^1.3.0
  dio: ^3.0.4
  path: ^1.6.4
  flutter_vector_icons: ^0.2.1

  








dev_dependencies:
  flutter_test:
    sdk: flutter
  link: ^1.0.0



flutter:
  uses-material-design: true
  assets:
     - images/
     - assets/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Bold.ttf

    - family: RalewayRegular
      fonts:
        - asset: fonts/Raleway-Regular.ttf


    - family: SFProText
      fonts:
        - asset: fonts/SFProText-Regular.ttf
