name: travel_world
description: Travel app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+4
  fluttertoast: ^3.1.0
  image_picker: 0.6.0+17
  shared_preferences: 0.5.3+4
  firebase_storage: 3.0.3
  cached_network_image: ^1.1.0
  intl: ^0.15.7
  firebase_messaging: 5.1.2
  flutter_local_notifications: ^0.8.0
  photo_view: ^0.4.2



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
     - images/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Bold.ttf


    - family: SFProText
      fonts:
        - asset: fonts/SFProText-Regular.ttf
